function stats = summarizeMeasurement(signals)
%SUMMARIZEMEASUREMENT  Return mean, minimum, maximum, and standard deviation.
%   STATS = SUMMARIZEMEASUREMENT(SIGNALS) uses the full-slice statistics
%   stored on each signal by READMEASUREMENT.
    arguments
        signals (1,:) struct
    end

    if isempty(signals)
        error("measurement:noSignal", ...
            "Read at least one channel before summarizing it.");
    end

    stats = table( ...
        string({signals.Name})', ...
        string({signals.Unit})', ...
        [signals.SampleCount]', ...
        [signals.Mean]', ...
        [signals.Minimum]', ...
        [signals.Maximum]', ...
        [signals.StandardDeviation]', ...
        VariableNames=["Name", "Unit", "Count", "Mean", "Minimum", "Maximum", "Std"]);
    disp(stats);
end
