%SIMPLE_APP  Small interactive sine-wave preview.
%   Drag the amplitude slider or change the frequency spinner.
%   The axes update immediately.

fig = uifigure( ...
    Name = "Sine Preview", ...
    Position = [120 120 720 460]);

root = uigridlayout(fig, [3 1], ...
    RowHeight = {'fit', 'fit', '1x'}, ...
    Padding = [16 16 16 16], ...
    RowSpacing = 12);

uilabel(root, ...
    Text = "Preview a sine wave. Move the controls to update the plot.", ...
    FontSize = 14);

controls = uigridlayout(root, [1 4], ...
    ColumnWidth = {'fit', '1x', 'fit', 110}, ...
    Padding = [0 0 0 0], ...
    ColumnSpacing = 12);
uilabel(controls, Text = "Amplitude");
ampSlider = uislider(controls, ...
    Limits = [0.1 2], ...
    Value = 1);
uilabel(controls, Text = "Frequency (Hz)");
freqSpinner = uispinner(controls, ...
    Limits = [1 10], ...
    Value = 2, ...
    Step = 1, ...
    RoundFractionalValues = "on");

ax = uiaxes(root);
ax.XLabel.String = "Time (s)";
ax.YLabel.String = "Amplitude";
title(ax, "Sine preview");
grid(ax, "on");

redraw = @(amplitude, frequency) drawWave(ax, amplitude, frequency);
ampSlider.ValueChangingFcn = @(~, event) redraw(event.Value, freqSpinner.Value);
ampSlider.ValueChangedFcn = @(~, ~) redraw(ampSlider.Value, freqSpinner.Value);
freqSpinner.ValueChangedFcn = @(~, ~) redraw(ampSlider.Value, freqSpinner.Value);
redraw(ampSlider.Value, freqSpinner.Value);

function drawWave(ax, amplitude, frequency)
t = linspace(0, 1, 500);
y = amplitude * sin(2 * pi * frequency * t);
plot(ax, t, y, LineWidth = 1.5);
xlim(ax, [0 1]);
ylim(ax, [-2.2 2.2]);
title(ax, sprintf("Sine preview   A = %.2f,  f = %g Hz", amplitude, frequency));
grid(ax, "on");
end
